import * as schedule from './review-schedule.js';

const DAYS = ['일','월','화','수','목','금','토'];
const PRESETS = [['기본',[1,3,7,14,30]],['촘촘하게',[1,2,4,7,15,30]],['시험 직전',[1,2,3,5,7]],['장기 암기',[1,3,7,21,60,120]]];
const MODES = [['망각곡선대로',{sameDay:true,nextDay:true,eve:false,curve:true}],['수업 리듬',{sameDay:true,nextDay:false,eve:true,curve:false}],['전날만',{sameDay:false,nextDay:false,eve:true,curve:false}]];
const MODE_LABELS = {sameDay:'수업 당일',nextDay:'다음 날',eve:'다음 수업 전날',curve:'망각곡선 간격'};
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const clone = value => JSON.parse(JSON.stringify(value));
const text = (value,max) => typeof value === 'string' && value.length <= max;
const date = value => typeof value === 'string' && schedule.validDate(value);
const md = value => date(value) ? `${Number(value.slice(5,7))}/${Number(value.slice(8,10))} (${DAYS[schedule.dayOfWeek(value)]})` : '날짜 미정';
const abortError = () => Object.assign(new Error('화면이 변경되었습니다.'),{name:'AbortError'});
const monthOf = value => value.slice(0,7)+'-01';
const itemName = item => item.subject || '과목 없음';
const SAFE_ERRORS = {stale_revision:'다른 기기에서 기록이 바뀌었어요. 최신 내용을 확인하고 다시 눌러 주세요.',undo_unavailable:'되돌릴 수 있는 8초가 지났거나 기록이 바뀌었어요.',invalid_input:'입력한 값과 글자 수를 확인해 주세요.',date_out_of_range:'날짜는 2000년부터 2100년 사이로 입력해 주세요.',routine_not_available:'이 루틴의 실행일과 오늘 또는 지난 날짜만 체크할 수 있어요.',recognition_disabled:'시간표 인식이 설정되지 않았어요. 아래에서 직접 입력해 주세요.',daily_limit:'오늘의 시간표 인식 횟수를 모두 사용했어요. 직접 입력하거나 내일 다시 시도해 주세요.'};
function friendlyError(error){if(error?.status===404)return '이 서버는 아직 리마인더를 지원하지 않거나 기록을 찾을 수 없어요. 서버 연결을 확인해 주세요.';const code=error?.detail||error?.message;return SAFE_ERRORS[code]||(typeof code==='string'&&/[가-힣]/.test(code)?code:'요청을 확인하지 못했습니다. 입력 내용과 연결을 확인하고 다시 시도해 주세요.');}

export function validReminderState(value) {
  if (!value || !Number.isSafeInteger(value.revision) || value.revision < 0 || !date(value.today)
    || !Array.isArray(value.items) || value.items.length>5000 || !Array.isArray(value.routines) || value.routines.length>500
    || !Array.isArray(value.exams) || value.exams.length>1000 || !value.settings
    || !schedule.validOffsets(value.settings.offsets) || !['due','subject'].includes(value.settings.sort)
    || (value.settings.sem_start!==null && !date(value.settings.sem_start))
    || !value.holidays || Array.isArray(value.holidays) || typeof value.holidays!=='object') return false;
  if (!Object.entries(value.holidays).every(([key,name])=>date(key)&&text(name,100))) return false;
  if (value.source_keys!==undefined && (!Array.isArray(value.source_keys)||value.source_keys.length>100000||!value.source_keys.every(key=>text(key,120)))) return false;
  if (!value.items.every(item=>UUID.test(item.id) && text(item.title,200) && text(item.subject,40) && text(item.memo,200)
    && date(item.learned) && date(item.base) && schedule.validOffsets(item.offsets) && Array.isArray(item.reviews)
    && item.reviews.length<=12 && item.reviews.every(date) && (!item.skipped || date(item.skipped))
    && (!item.moved || (Number.isSafeInteger(item.moved.stage)&&date(item.moved.date))))) return false;
  if (!value.routines.every(row=>UUID.test(row.id)&&text(row.name,60)&&text(row.tag,40)&&date(row.start)
    && (!row.end||date(row.end)) && Array.isArray(row.days)&&row.days.every(day=>Number.isInteger(day)&&day>=0&&day<=6)
    && Array.isArray(row.done)&&row.done.every(date)&&Number.isInteger(row.count)&&row.count>=0
    && typeof row.numbered==='boolean'&&Number.isInteger(row.num_start)&&row.num_start>=1)) return false;
  if (!value.exams.every(row=>UUID.test(row.id)&&text(row.subject,40)&&['mid','final'].includes(row.kind)&&date(row.date)
    && Number.isInteger(row.rounds)&&row.rounds>=1&&row.rounds<=5&&[3,5,7,10,14].includes(row.lead)
    && row.done&&typeof row.done==='object'&&!Array.isArray(row.done))) return false;
  if (value.timetable && (!Array.isArray(value.timetable.classes)||value.timetable.classes.length>60
    || !date(value.timetable.from)||!date(value.timetable.through)||value.timetable.until&&!date(value.timetable.until)
    || !value.timetable.mode || !Object.keys(MODE_LABELS).every(key=>typeof value.timetable.mode[key]==='boolean')
    || !value.timetable.classes.every(row=>text(row.subject,40)&&Number.isInteger(row.day)&&row.day>=0&&row.day<=6
      && (row.start===''||/^\d{2}:\d{2}$/.test(row.start))&&(row.end===''||/^\d{2}:\d{2}$/.test(row.end))&&text(row.room,120)))) return false;
  return true;
}

// The reference planner's SVG sampling, expressed as DOM geometry rather than HTML.
export function memoryCurve(item,today) {
  const base=item.catchup?item.learned:item.base, past=[base,...item.reviews].map(value=>schedule.diffDays(base,value));
  const future=schedule.projected(item,today).map((row,index)=>schedule.diffDays(base,index===0&&row.date<today?today:row.date));
  const events=[...past,...future],todayT=schedule.diffDays(base,today);
  const lastGap=item.offsets.at(-1)-(item.offsets.at(-2)||0);
  const end=Math.max((events.at(-1)||0)+Math.max(4,Math.round(lastGap*.5)),todayT+2,6);
  const points=[];
  for(let i=0;i<events.length;i++){
    const a=events[i],b=events[i+1]??end,count=Math.max(6,Math.ceil((b-a)/end*360));
    for(let s=0;s<=count;s++){const t=a+(b-a)*s/count;points.push({t,r:Math.exp(-(t-a)/2.5**i),segment:i});}
  }
  const remembered=Math.min(1,Math.exp(-Math.max(0,todayT-past.at(-1))/2.5**(past.length-1)));
  if(todayT>=0)points.push({t:todayT,r:remembered,segment:past.length-1});
  points.sort((a,b)=>a.segment-b.segment||a.t-b.t);
  return {base,end,events,todayT,remembered,past:points.filter(p=>p.segment<past.length&&p.t<=todayT),
    future:points.filter(p=>p.segment>=past.length-1&&p.t>=Math.max(0,todayT)),
    baseline:Array.from({length:201},(_,i)=>({t:end*i/200,r:Math.exp(-end*i/200)}))};
}

export function createReminder({container,api,scopeKey}) {
  const document=container.ownerDocument,win=document.defaultView||globalThis;
  let context=null,state=null,visible=false,refreshTimer=null,undoTimer=null,confirmTimer=null;
  let busy=false,reading=false,readSequence=0,intent=null,undo=null,confirmed='',moving=null,dragging=null;
  let selectedDay='',month='',selectedItem='',filter='active',subjectFilter='',query='',editorDirty=false,editorVisible=false,editorRevision=0;
  let catchupRows=[],parseBusy=false,destroyed=false,recordsLimit=50;
  let scheduleCache=new Map();
  let modeDraft=null,modeApply=false;
  const reviewDrafts=new Map(),placeDrafts=new Map();
  const el=(tag,value='',className='')=>{const node=document.createElement(tag);if(value)node.textContent=value;if(className)node.className=className;return node;};
  const setData=(node,key,value)=>{node.dataset[key]=value;return node;};
  const button=(label,handler,{primary=false,action='',disabled=false}={})=>{
    const node=el('button',label,primary?'rv-primary':'');node.type='button';node.disabled=disabled;
    if(action)node.dataset.action=action;node.onclick=()=>run(handler);return node;
  };
  const control=(type,value='',max)=>{const node=el(type==='textarea'?'textarea':'input');if(type!=='textarea')node.type=type;node.value=value;if(max)node.maxLength=max;return node;};
  const label=(name,node,wide=false)=>{const wrapper=el('label',name,wide?'rv-wide':'');node.setAttribute('aria-label',name);wrapper.append(node);return wrapper;};
  const check=(name,checked=false)=>{const node=control('checkbox');node.checked=checked;const wrapper=label(name,node);wrapper.className='rv-check';return {node,wrapper};};
  const select=(entries,value)=>{const node=el('select');for(const [key,name]of entries){const option=el('option',name);option.value=String(key);node.append(option);}if(value!==undefined)node.value=String(value);return node;};
  const badge=(name,warn=false)=>el('span',name,'rv-badge'+(warn?' rv-warning':''));
  const panel=(name,className,description='')=>{const node=el('section','','rv-section '+className),head=el('h2',name);node.append(head);if(description)node.append(el('p',description,'rv-panel-sub'));return node;};
  const valid=captured=>!destroyed&&context===captured&&!!captured&&captured.key===scopeKey()&&!captured.controller.signal.aborted;
  const currentItem=id=>state?.items.find(row=>row.id===id);
  function message(value){status.textContent=value;}
  async function run(fn){const captured=context;if(!valid(captured))return;try{return await fn();}catch(error){if(valid(captured)&&error?.name!=='AbortError')message(friendlyError(error));}}
  async function request(path,options={},captured=context,timeout){if(!valid(captured))throw abortError();const value=await api(path,{...options,signal:captured.controller.signal},timeout);if(!valid(captured))throw abortError();return value;}
  function actionButton(name,action,payload,extra={}){const captured=context;return button(name,()=>valid(captured)&&mutate(action,typeof payload==='function'?payload():payload),{...extra,action,disabled:busy||!!intent});}
  function confirmButton(name,key,action,payload){const captured=context;return button(confirmed===key?'한 번 더 눌러 확인':name,()=>{
    if(!valid(captured)||busy||intent)return;if(confirmed===key){confirmed='';return mutate(action,payload);}
    confirmed=key;clearTimeout(confirmTimer);confirmTimer=setTimeout(()=>{confirmed='';if(valid(captured))render();},8000);render();
  },{action,disabled:busy||!!intent});}
  const header=el('header','','rv-header'),headline=el('div','','rv-headline'),heading=el('h1','오늘의 배움을 오래 기억하도록'),dateLine=el('p','','rv-date'),stats=el('div','','rv-stats');
  headline.append(dateLine,heading,stats);const topActions=el('div','','rv-actions');
  const theme=button('다크 모드',()=>{const dark=!container.classList.contains('rv-dark');container.classList.toggle('rv-dark',dark);container.classList.toggle('rv-light',!dark);theme.textContent=dark?'라이트 모드':'다크 모드';theme.setAttribute('aria-pressed',String(dark));});theme.setAttribute('aria-pressed','false');
  topActions.append(theme,button('새로고침',()=>refresh()));header.append(headline,topActions);
  const status=el('p','','rv-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
  const generationNotice=el('p','','rv-move-bar');generationNotice.hidden=true;generationNotice.dataset.notice='generation';generationNotice.setAttribute('role','status');
  const uncertain=el('div','','rv-move-bar');uncertain.hidden=true;uncertain.append(el('p','요청 결과를 아직 확인하지 못했습니다. 같은 요청으로 확인하면 중복 저장하지 않습니다.'),button('같은 요청 확인 · 재시도',()=>retryIntent()));
  const welcome=el('p','공부한 내용이나 시간표를 등록하면 복습할 날을 알려 드려요. 아래에서 첫 기록을 추가하거나 루틴을 만들어 보세요.','rv-empty');
  const workbench=el('div','','rv-workbench'),leftColumn=el('div','','rv-column rv-column-left'),rightColumn=el('div','','rv-column rv-column-right');
  const todayPanel=panel('오늘의 복습','rv-today'),queueHead=el('div','','rv-bar'),sortControls=el('div','','rv-actions'),todayBody=el('div','','rv-stack');
  for(const [value,name]of [['due','밀린 순'],['subject','과목별']]){const b=button(name,()=>mutate('settings.save',{sort:value}),{action:'sort-'+value});b.dataset.sort=value;sortControls.append(b);}queueHead.append(el('p','작은 복습을 하나씩 이어가요.','rv-muted'),sortControls);todayPanel.append(queueHead,todayBody);
  const addPanel=panel('새로 공부한 내용','rv-add','공부한 날을 기준으로 복습 날짜를 계산해요.'),addForm=el('form','','rv-form');
  const titleInput=control('text','',200),subjectInput=control('text','',40),memoInput=control('textarea','',200),learnedInput=control('date');titleInput.required=true;learnedInput.required=true;
  memoInput.rows=1;
  const addPreview=el('div','','rv-preview rv-wide'),addSubmit=el('button','추가하기','rv-primary rv-wide rv-submit');addSubmit.type='submit';
  addForm.append(label('공부한 내용',titleInput,true),label('과목 · 선택',subjectInput),label('공부한 날',learnedInput),label('메모 · 선택',memoInput,true),addPreview,addSubmit);addPanel.append(addForm);
  learnedInput.oninput=()=>previewAdded();
  addForm.onsubmit=event=>{event.preventDefault();return run(async()=>{const submitted={title:titleInput.value,memo:memoInput.value};if(await mutate('item.add',{title:submitted.title.trim(),subject:subjectInput.value.trim(),memo:submitted.memo.trim(),learned:learnedInput.value})){if(titleInput.value===submitted.title)titleInput.value='';if(memoInput.value===submitted.memo)memoInput.value='';titleInput.focus();}});};
  const calendarPanel=panel('복습 달력','rv-calendar','날짜를 누르면 그날 할 복습이 보여요. 카드를 끌어다 놓거나 옮기기 버튼으로 날짜를 바꿀 수 있어요.'),calendarBar=el('div','','rv-bar rv-calendar-nav'),monthLabel=el('h3'),calendarGrid=el('div','','rv-days'),dayDetail=el('div','','rv-day-detail'),moveBar=el('div','','rv-move-bar');
  calendarBar.append(button('이전 달',()=>changeMonth(-1)),monthLabel,button('오늘',()=>{month=monthOf(state.today);selectedDay=state.today;renderCalendar();}),button('다음 달',()=>changeMonth(1)));moveBar.hidden=true;
  calendarPanel.append(calendarBar,moveBar,calendarGrid,el('small','● 예정 · ○ 복습함 · ■ 공부 · ◆ 시험 · ━ 루틴'),dayDetail);
  const nextPanel=panel('앞으로 7일','rv-next','날짜별로 어떤 내용을 복습할지 미리 보여드려요.'),nextBody=el('div','','rv-stack');nextPanel.append(nextBody);
  const curvePanel=panel('기억 곡선 · 추정','rv-full rv-curve','선택한 기록의 복습 일정과 회차별 기록을 함께 확인해요.'),curveSelect=select([],''),curveBody=el('div','','rv-stack');curveSelect.setAttribute('aria-label','기억 곡선을 볼 기록');curveSelect.onchange=()=>{selectedItem=curveSelect.value;renderCurve();};curvePanel.append(curveSelect,curveBody);
  // Keep the daily workflow beside the calendar. The supplementary curve
  // follows all records below; CSS unwraps these columns on small screens.
  leftColumn.append(todayPanel,addPanel,nextPanel);rightColumn.append(calendarPanel);workbench.append(leftColumn,rightColumn);
  const routinePanel=panel('루틴','rv-full rv-routines','매일 또는 정한 요일의 공부예요. 해당하는 날에는 오늘의 복습 위에 체크리스트가 보여요.'),routineBody=el('div','','rv-routine-list');
  const routineForm=el('form','','rv-form rv-routine-form'),routineName=control('text','',60),routineTag=control('text','',40),routineStart=control('date'),routineEnd=control('date'),routineCount=control('number','0'),routineNum=control('number','1'),routineNumbered=check('번호 붙이기');
  routineName.required=true;routineCount.min='0';routineCount.max='10000';routineNum.min='1';routineNum.max='10000';const routineDays=el('div','','rv-chips rv-wide'),routineDayChecks=[];
  routineDays.append(button('매일',()=>{routineDayChecks.forEach(node=>node.checked=false);}));for(let day=1;day<=7;day++){const c=check(DAYS[day%7]);routineDayChecks[day%7]=c.node;routineDays.append(c.wrapper);}
  const routineSubmit=el('button','루틴 추가','rv-primary');routineSubmit.type='submit';
  const routineDayField=el('div','','rv-routine-days');routineDayField.append(el('span','요일','rv-field-name'),routineDays);
  const routineNumberField=el('div','','rv-routine-number');routineNumberField.append(routineNumbered.wrapper,label('시작 번호',routineNum));
  const routineNameField=label('할 일',routineName);routineNameField.classList.add('rv-routine-name');
  const routineStartField=label('시작일',routineStart),routineEndField=label('종료일 · 선택',routineEnd),routineCountField=label('횟수 · 0이면 무제한',routineCount);routineStartField.classList.add('rv-routine-date');routineEndField.classList.add('rv-routine-date');routineCountField.classList.add('rv-routine-count');
  routineForm.append(routineNameField,label('분류 · 선택',routineTag),routineDayField,routineStartField,routineEndField,routineCountField,routineNumberField,routineSubmit);routinePanel.append(routineForm,routineBody);
  routineForm.onsubmit=event=>{event.preventDefault();return run(async()=>{const submitted=routineName.value;if(await mutate('routine.add',{name:submitted.trim(),tag:routineTag.value.trim(),days:routineDayChecks.flatMap((node,i)=>node.checked?[i]:[]),start:routineStart.value,end:routineEnd.value||null,count:Number(routineCount.value||0),numbered:routineNumbered.node.checked,num_start:Number(routineNum.value||1)})){if(routineName.value===submitted)routineName.value='';}});};
  const examPanel=panel('시험 대비','rv-full rv-exams','시험 날짜를 넣으면 범위 안의 수업을 모아 회독표를 만들어요.'),examBody=el('div','','rv-exam-list'),examForm=el('form','','rv-form rv-exam-form');
  const examSubject=control('text','',40),examKind=select([['mid','중간고사'],['final','기말고사']],'mid'),examDate=control('date'),examRounds=select([1,2,3,4,5].map(n=>[n,n+'회독']),3),examLead=select([3,5,7,10,14].map(n=>[n,n+'일 전']),7),semesterStart=control('date');examSubject.required=true;examDate.required=true;
  const subjectList=el('datalist');subjectList.id='reminder-subjects';examSubject.setAttribute('list',subjectList.id);subjectInput.setAttribute('list',subjectList.id);
  const examSubmit=el('button','시험 저장','rv-primary');examSubmit.type='submit';examForm.append(label('과목',examSubject),label('시험 종류',examKind),label('시험일',examDate),label('회독 수',examRounds),label('벼락치기 시작',examLead),examSubmit);
  const semesterBar=el('div','','rv-actions rv-semester');semesterBar.append(label('개강일',semesterStart),button('개강일 저장',()=>mutate('settings.save',{sem_start:semesterStart.value||null})));examPanel.append(examForm,semesterBar,subjectList,examBody);
  examForm.onsubmit=event=>{event.preventDefault();return run(()=>mutate('exam.save',{subject:examSubject.value.trim(),kind:examKind.value,date:examDate.value,rounds:Number(examRounds.value),lead:Number(examLead.value)}));};
  const timetablePanel=panel('수업 시간표','rv-full rv-timetable','매주 듣는 수업을 등록하면 수업이 있는 날마다 복습 기록이 자동으로 추가돼요.'),timetableView=el('div','','rv-stack'),timetableEditor=el('div','','rv-stack'),classRows=el('div'),weekPreview=el('div'),timetableForm=el('form','','rv-stack');timetableEditor.hidden=true;
  const ttFrom=control('date'),ttUntil=control('date'),ttDates=el('div','','rv-form');ttDates.append(label('자동 등록 시작일',ttFrom),label('종강일 · 선택',ttUntil));
  const parsePanel=el('details'),parseText=control('textarea','',6000),parseFile=control('file'),parseStatus=el('p','','rv-muted');parseText.rows=4;parseFile.accept='image/png,image/jpeg,image/webp';
  parsePanel.append(el('summary','이미지 · 글에서 시간표 인식'),el('p','인식 버튼을 누르면 선택한 이미지 또는 글을 NOVA AI에 보냅니다. 이미지는 서버 메모리에서만 처리합니다. 결과를 직접 확인한 뒤 저장하세요.','rv-muted'),label('시간표 글 · 6,000자 이하',parseText),label('시간표 이미지 · PNG/JPEG/WebP, 10MB 이하',parseFile),button('글 인식',()=>parseTimetable('text'),{action:'parse-text'}),button('이미지 인식',()=>parseTimetable('image'),{action:'parse-image'}),parseStatus);
  const ttSubmit=el('button','시간표 저장','rv-primary');ttSubmit.type='submit';timetableForm.append(classRows,button('수업 한 줄 추가',()=>addClassRow()),ttDates,ttSubmit);
  timetableEditor.append(parsePanel,timetableForm,el('h3','주간 시간표 미리보기'),weekPreview,button('편집 닫기',()=>{editorVisible=false;timetableEditor.hidden=true;timetableView.hidden=false;}));timetablePanel.append(timetableView,timetableEditor);
  timetableForm.onsubmit=event=>{event.preventDefault();return run(async()=>{const revision=editorRevision;if(await mutate('timetable.save',{classes:readClassRows(),from:ttFrom.value,until:ttUntil.value||null,mode:state.timetable?.mode||schedule.DEFAULT_MODE})){if(editorRevision===revision){editorVisible=false;editorDirty=false;timetableEditor.hidden=true;timetableView.hidden=false;}renderTimetable();}});};
  const catchupPanel=el('section','','rv-stack rv-move-bar');catchupPanel.hidden=true;const catchupStart=control('date'),catchupPerDay=select([[3,'하루 3개'],[5,'하루 5개'],[8,'하루 8개'],[12,'하루 12개'],[0,'전부 오늘']],5),catchupChoices=el('div','','rv-stack'),catchupSummary=el('p');
  const catchupPerLabel=label('하루 개수',catchupPerDay);catchupPanel.append(el('h3','지난 수업 불러오기'),el('p','개강일부터 오늘까지의 수업을 다시 확인할 수 있어요. 이미 등록한 수업은 중복으로 불러오지 않아요. 공휴일에도 수업했다면 해당 날짜를 직접 선택하세요.','rv-muted'),label('개강일',catchupStart),button('불러올 수업 미리보기',()=>previewCatchup()),catchupPerLabel,catchupChoices,catchupSummary,button('선택한 지난 수업 불러오기',()=>saveCatchup(),{action:'timetable.catchup'}),button('닫기',()=>{catchupPanel.hidden=true;}));catchupPerDay.onchange=()=>updateCatchupSummary();timetablePanel.append(catchupPanel);
  const recordsPanel=panel('전체 기록','rv-full rv-records'),recordsBar=el('div','','rv-actions rv-record-tools'),search=control('search'),recordsSubjects=el('div','','rv-chips'),recordsBody=el('div','','rv-stack');search.placeholder='제목 · 과목 · 메모 검색';search.setAttribute('aria-label','전체 기록 검색');search.oninput=()=>{query=search.value;recordsLimit=50;renderRecords();};
  for(const [value,name]of [['active','진행 중'],['done','복습 끝'],['skipped','건너뛴 복습'],['all','전체']]){const b=button(name,()=>{filter=value;recordsLimit=50;renderRecords();});b.dataset.filter=value;recordsBar.append(b);}recordsBar.append(search);recordsPanel.append(recordsBar,recordsSubjects,recordsBody);
  const skippedShortcut=button('건너뛴 복습 0',()=>{filter='skipped';subjectFilter='';query='';search.value='';recordsLimit=50;renderRecords();recordsPanel.scrollIntoView?.({block:'start'});for(const b of recordsBar.children)if(b.dataset?.filter==='skipped')b.focus({preventScroll:true});});skippedShortcut.classList.add('rv-badge');
  const settingsPanel=panel('복습 간격 설정','rv-full rv-settings','설정을 바꾸면 새로 추가하는 기록부터 적용합니다.'),offsetInput=control('text'),presetButtons=el('div','','rv-actions');offsetInput.setAttribute('aria-label','복습 간격 · 쉼표로 구분');for(const [name,offsets]of PRESETS)presetButtons.append(button(name,()=>{offsetInput.value=offsets.join(', ');}));
  const settingsGrid=el('div','','rv-settings-grid'),settingsControls=el('div','','rv-stack'),offsetRow=el('div','','rv-actions rv-offset-row'),modelNote=el('aside','','rv-model-note');
  offsetRow.append(offsetInput,button('복습 간격 저장',()=>{const offsets=offsetInput.value.split(/[\s,]+/).filter(Boolean).map(Number);if(!schedule.validOffsets(offsets))throw Error('복습 간격은 0~365일의 중복 없는 오름차순 정수 1~12개로 입력해 주세요.');return mutate('settings.save',{offsets});}));
  settingsControls.append(presetButtons,offsetRow,el('p','숫자는 공부한 날로부터 며칠째인지를 뜻해요. 0~365일, 오름차순으로 1~12개를 입력하세요.','rv-muted'));
  modelNote.append(el('h3','기억 곡선은 추정치예요'),el('p','복습하면 기억률이 다시 올라가고 이후에는 더 천천히 잊힌다고 가정한 모델이에요. 실제 기억은 내용의 난이도와 공부 방식에 따라 달라요.','rv-muted'));settingsGrid.append(settingsControls,modelNote);settingsPanel.append(settingsGrid);
  const toast=el('div','','rv-toast rv-actions');toast.hidden=true;toast.setAttribute('role','status');
  container.classList.add('reminder');container.replaceChildren(header,status,generationNotice,uncertain,welcome,workbench,routinePanel,examPanel,timetablePanel,recordsPanel,curvePanel,settingsPanel,toast);
  container.onkeydown=event=>{if(event.key==='Escape'&&moving){moving=null;renderCalendar();}};
  function reset(){context?.controller.abort();context=null;visible=false;state=null;busy=false;reading=false;parseBusy=false;intent=null;undo=null;confirmed='';moving=null;dragging=null;++readSequence;clearTimeout(refreshTimer);clearTimeout(undoTimer);clearTimeout(confirmTimer);refreshTimer=undoTimer=confirmTimer=null;container.hidden=true;
    titleInput.value=subjectInput.value=memoInput.value=learnedInput.value='';routineName.value=routineTag.value=routineStart.value=routineEnd.value='';routineDayChecks.forEach(node=>node.checked=false);routineCount.value='0';routineNum.value='1';routineNumbered.node.checked=false;
    examSubject.value=examDate.value=semesterStart.value='';parseText.value=parseFile.value='';parseStatus.textContent='';offsetInput.value='';editorDirty=false;editorVisible=false;modeDraft=null;modeApply=false;reviewDrafts.clear();placeDrafts.clear();classRows.replaceChildren();timetableEditor.hidden=true;timetableView.hidden=false;catchupPanel.hidden=true;catchupRows=[];search.value='';query='';filter='active';subjectFilter='';selectedDay=month=selectedItem='';message('');toast.hidden=true;uncertain.hidden=true;
    ttFrom.value=ttUntil.value=catchupStart.value='';recordsLimit=50;editorRevision++;scheduleCache.clear();generationNotice.hidden=true;generationNotice.textContent='';
    for(const node of [todayBody,calendarGrid,dayDetail,nextBody,curveBody,routineBody,examBody,timetableView,recordsBody,recordsSubjects,stats,catchupChoices,catchupSummary,weekPreview,subjectList])node.replaceChildren();curveSelect.replaceChildren();header.hidden=true;workbench.hidden=true;for(const panel of [routinePanel,examPanel,timetablePanel,recordsPanel,curvePanel,settingsPanel])panel.hidden=true;}
  function hide(){visible=false;container.hidden=true;context?.controller.abort();context=null;reading=false;busy=false;parseBusy=false;clearTimeout(refreshTimer);refreshTimer=null;++readSequence;}
  async function open(){if(destroyed)return;if(context?.key!==scopeKey()&&context!==null)reset();if(state&&lastScope!==scopeKey())reset();lastScope=scopeKey();visible=true;container.hidden=false;context?.controller.abort();context={key:scopeKey(),controller:new AbortController()};return run(()=>refresh());}
  let lastScope='';
  async function refresh(){const captured=context;if(!valid(captured)||reading||busy||parseBusy)return;reading=true;const sequence=++readSequence;
    try{const result=await request('/review/state',{},captured);if(sequence!==readSequence)return;accept(result);if(!intent)message('');}
    finally{if(valid(captured)){reading=false;scheduleRefresh();}}}
  function scheduleRefresh(){clearTimeout(refreshTimer);if(visible&&valid(context)){refreshTimer=setTimeout(()=>void run(()=>refresh()),30000);refreshTimer?.unref?.();}}
  function accept(result){const next=result?.state||result;if(!validReminderState(next))throw Error('복습 데이터 형식을 확인하지 못했습니다. 새로고침해 주세요.');if(state&&next.revision<state.revision)return;if(state&&JSON.stringify(state)===JSON.stringify(next))return;
    const initial=!state;state=clone(next);if(initial){selectedDay=state.today;month=monthOf(state.today);learnedInput.value=routineStart.value=state.today;semesterStart.value=state.settings.sem_start||'';offsetInput.value=state.settings.offsets.join(', ');}render();}
  async function mutate(action,payload){if(busy||parseBusy||!state)return false;if(intent){message('먼저 결과를 확인하지 못한 요청을 확인해 주세요.');return false;}
    intent={request_id:crypto.randomUUID(),revision:state.revision,action,payload:clone(payload)};return retryIntent();}
  async function retryIntent(){if(!intent||busy||!valid(context))return false;const captured=context,sent=intent;busy=true;uncertain.hidden=true;render();
    try{const result=await request('/review/actions',{method:'POST',body:JSON.stringify(sent)},captured);if(intent!==sent)return false;accept(result);intent=null;if(sent.action==='timetable.mode'){modeDraft=null;modeApply=false;}if(sent.action==='undo'){undo=null;toast.hidden=true;clearTimeout(undoTimer);}message(typeof result.message==='string'?result.message:'저장했어요.');if(result.undo)showUndo(result.undo);return true;}
    catch(error){if(!valid(captured))return false;if(error?.status===409){intent=null;message('다른 기기에서 기록이 바뀌었습니다. 최신 내용을 불러왔어요. 입력한 내용은 그대로입니다.');busy=false;await refresh();}
      else if(Number.isInteger(error?.status)&&error.status>=400&&error.status<500){intent=null;message(friendlyError(error));}
      else if(error?.name!=='AbortError'){message('연결이 끊겨 저장 결과를 확인하지 못했습니다. 같은 요청으로 확인해 주세요.');uncertain.hidden=false;}return false;}
    finally{if(valid(captured)){busy=false;uncertain.hidden=!intent;render();scheduleRefresh();}}}
  function showUndo(value){clearTimeout(undoTimer);if(!text(value.token,2000))return;undo={token:value.token,expires:Math.min(Date.now()+8000,Date.parse(value.expires_at)||Date.now()+8000)};
    toast.replaceChildren(el('span','저장했어요. 8초 동안 되돌릴 수 있어요.'),button('되돌리기',()=>{if(!undo||Date.now()>undo.expires){toast.hidden=true;return;}const token=undo.token;return mutate('undo',{token});},{action:'undo'}));toast.hidden=false;undoTimer=setTimeout(()=>{undo=null;toast.hidden=true;},Math.max(0,undo.expires-Date.now()));undoTimer?.unref?.();}
  function previewAdded(){if(!state||!date(learnedInput.value)){addPreview.textContent='공부한 날을 선택해 주세요.';return;}addPreview.replaceChildren(el('span','복습일'));for(const offset of state.settings.offsets)addPreview.append(el('span',md(schedule.addDays(learnedInput.value,offset)),'rv-preview-date'));}
  function render(){if(!state)return;header.hidden=false;workbench.hidden=false;for(const panel of [routinePanel,examPanel,timetablePanel,recordsPanel,curvePanel,settingsPanel])panel.hidden=false;
    generationNotice.hidden=!state.generation_error;generationNotice.textContent=state.generation_error==='schedule_range_limit'
      ? '수업 자동 등록을 잠시 멈췄어요. 저장된 기록은 그대로입니다. 시간표의 시작일을 확인하고 지난 수업은 10년 이내 범위로 나누어 불러와 주세요.'
      : state.generation_error?'기록 개수 제한으로 수업 자동 등록을 잠시 멈췄어요. 저장된 기록은 그대로입니다. 전체 기록을 확인하고 필요한 기록을 정리해 주세요.':'';
    scheduleCache=new Map();for(const item of state.items)for(const row of schedule.projected(item,state.today)){if(!scheduleCache.has(row.date))scheduleCache.set(row.date,[]);scheduleCache.get(row.date).push({item,...row});}
    dateLine.textContent=state.today.replace(/-/g,'.')+' '+DAYS[schedule.dayOfWeek(state.today)]+'요일';const due=schedule.dueItems(state.items,state.today,state.settings.sort);heading.textContent=`오늘 복습할 내용 ${due.length}개`;
    const active=state.items.filter(item=>!item.skipped),done=active.filter(item=>!schedule.nextDue(item));const routineToday=schedule.routinesOn(state.routines,state.today);const upcoming=state.exams.filter(exam=>exam.date>=state.today).sort((a,b)=>a.date.localeCompare(b.date))[0];
    stats.replaceChildren(badge(`밀린 복습 ${due.filter(item=>schedule.nextDue(item)<state.today).length}`,true),badge(`오늘 예정 ${due.filter(item=>schedule.nextDue(item)===state.today).length}`),badge(`7일 안에 ${active.filter(item=>{const d=schedule.nextDue(item);return d&&d>state.today&&d<=schedule.addDays(state.today,7);}).length}`),badge(`복습 끝 ${done.length}/${active.length}`),badge(`루틴 ${routineToday.filter(({routine})=>routine.done.includes(state.today)).length}/${routineToday.length}`));if(upcoming)stats.append(badge(`다음 시험 D-${schedule.diffDays(state.today,upcoming.date)}`));
    const skippedCount=state.items.length-active.length;skippedShortcut.textContent=`건너뛴 복습 ${skippedCount}`;skippedShortcut.setAttribute('aria-label',`건너뛴 복습 ${skippedCount}개 보기`);stats.append(skippedShortcut);
    welcome.hidden=!!(state.items.length||state.routines.length||state.timetable);for(const b of sortControls.children)b.setAttribute('aria-pressed',String(b.dataset.sort===state.settings.sort));
    for(const node of [addSubmit,routineSubmit,examSubmit,ttSubmit])node.disabled=busy||!!intent;parsePanel.hidden=state.recognition?.enabled!==true;
    renderToday();renderCalendar();renderNext();renderCurve();renderRoutines();renderExams();renderTimetable();renderRecords();previewAdded();
    subjectList.replaceChildren();for(const subject of [...new Set([...state.items.map(row=>row.subject),...(state.timetable?.classes||[]).map(row=>row.subject)])].filter(Boolean).sort()){const option=el('option');option.value=subject;subjectList.append(option);}}
  function examInfo(exam){const sem=state.settings.sem_start||state.timetable?.from||state.today;const sessions=schedule.examSessions(exam,sem,state.timetable,state.holidays,state.exams,state.items,state.today);return {sessions,stats:schedule.examStats(exam,sessions,state.today),sem};}
  function examLabel(exam){return `${exam.subject} ${exam.kind==='mid'?'중간고사':'기말고사'}`;}
  function routineCheck(routine,day){const row=check(schedule.routineTitle(routine,schedule.routineN(routine,day)),routine.done.includes(day));row.node.disabled=day>state.today||busy||!!intent;row.node.dataset.action='routine.check';if(row.node.checked)row.wrapper.classList.add('rv-struck');const captured=context;row.node.onchange=()=>run(()=>valid(captured)&&mutate('routine.check',{id:routine.id,date:day,checked:row.node.checked}));return row.wrapper;}
  function renderToday(){todayBody.replaceChildren();for(const exam of state.exams){const info=examInfo(exam);if(['cram','today'].includes(info.stats.phase))todayBody.append(el('p',`${examLabel(exam)} ${info.stats.phase==='today'?'D-day':`D-${info.stats.days_left}`} · 오늘 회독 목표 ${info.stats.target}개`,'rv-move-bar'));}
    const routines=schedule.routinesOn(state.routines,state.today);if(routines.length){const block=el('div','','rv-stack');block.append(el('h3',`오늘의 루틴 ${routines.filter(({routine})=>routine.done.includes(state.today)).length} / ${routines.length}`));for(const {routine}of routines)block.append(routineCheck(routine,state.today));todayBody.append(block);}
    const due=schedule.dueItems(state.items,state.today,state.settings.sort);if(!due.length)todayBody.append(el('p','오늘 복습할 내용이 없어요. 새로 공부한 내용을 남겨 보세요.','rv-empty'));
    if(state.settings.sort==='subject'){for(const group of schedule.groupDueItems(state.items,state.today)){const box=el('div','','rv-group'),head=el('div','','rv-bar');head.append(el('h3',`${group.subject||'과목 없음'} · ${group.items.length}개 · 밀림 ${group.overdue}개`),actionButton('모두 복습 완료','item.group_review',{ids:group.items.map(item=>item.id)}));box.append(head,...group.items.map(item=>itemCard(item,{subject:false})));todayBody.append(box);}}
    else for(const item of due)todayBody.append(itemCard(item));}
  function itemCard(item,{subject=true,records=false}={}){const due=schedule.nextDue(item),card=el('article','','rv-card'+(due&&due<state.today?' rv-overdue':'')+(item.skipped?' rv-ended':''));card.dataset.item=item.id;
    const chips=el('div','','rv-chips');if(subject)chips.append(badge(itemName(item)));chips.append(badge(`${Math.min(item.reviews.length+1,item.offsets.length)}/${item.offsets.length}회차`));if(item.skipped)chips.append(badge('건너뜀'));else if(due)chips.append(badge(due<state.today?`${schedule.diffDays(due,state.today)}일 밀림`:due===state.today?'오늘':md(due),due<state.today));else chips.append(badge('복습 끝'));if(item.catchup)chips.append(badge('따라잡기'));
    if(item.source==='timetable'&&state.timetable){const next=schedule.nextClassDate(item.subject,state.today,state.timetable,state.holidays);if(next)chips.append(badge(next===schedule.addDays(state.today,1)?'내일 수업 전':`다음 수업 ${md(next)}`));}
    const progress=el('div','','rv-progress');progress.setAttribute('aria-label',`${item.offsets.length}회 중 ${item.reviews.length}회 완료`);for(let i=0;i<item.offsets.length;i++)progress.append(el('span','',i<item.reviews.length?'rv-done':''));
    const actions=el('div','','rv-actions');if(item.skipped)actions.append(actionButton('복습 다시 시작','item.unskip',{id:item.id}));else if(due)actions.append(actionButton('복습 완료','item.review',{id:item.id},{primary:true}),actionButton('복습 건너뛰기','item.skip',{id:item.id}));
    const captured=context;if(!item.skipped)actions.append(button('기록 보기',()=>{if(valid(captured)){selectedItem=item.id;renderCurve();curvePanel.scrollIntoView?.({behavior:'smooth',block:'start'});curveSelect.focus();}}));if(records)actions.append(confirmButton('삭제','item:'+item.id,'item.delete',{id:item.id}));
    card.append(chips,el('h3',item.title));if(item.memo)card.append(el('p',item.memo,'rv-muted'));card.append(el('small',`공부한 날 ${md(item.learned)} · 추정 기억률 ${Math.round(schedule.retention(item,state.today)*100)}%`),progress,actions);if(due)makeDraggable(card,item.id);return card;}
  function makeDraggable(node,id){node.draggable=true;node.ondragstart=event=>{if(!currentItem(id)||busy||intent){event.preventDefault();return;}dragging=id;event.dataTransfer?.setData('application/x-yeobaek-review',id);if(event.dataTransfer)event.dataTransfer.effectAllowed='move';container.classList.add('rv-dragging');};node.ondragend=()=>{dragging=null;container.classList.remove('rv-dragging');};}
  function beginMove(id){moving=id;message('옮길 날짜를 누르세요. 지난 날짜를 누르면 그날 복습한 걸로 기록해요.');renderCalendar();calendarPanel.scrollIntoView?.({behavior:'smooth',block:'start'});}
  async function place(id,day){const item=currentItem(id);if(!item)return;const changed=schedule.placeReview(item,day,state.today);if(JSON.stringify(changed)===JSON.stringify(item)){moving=null;renderCalendar();message('이미 그날 예정이에요.');return;}if(await mutate('item.move',{id,date:day})){moving=null;renderCalendar();message(day<state.today?`${md(day)}에 복습한 것으로 기록했어요.`:day===state.today?'오늘로 당겨왔어요':`${md(day)} (${schedule.diffDays(state.today,day)}일 뒤)로 옮겼어요.`);}}
  function changeMonth(delta){const current=month||monthOf(state.today),year=Number(current.slice(0,4)),m=Number(current.slice(5,7));const target=new Date(Date.UTC(year,m-1+delta,1));const next=target.toISOString().slice(0,10);if(next>='2000-01-01'&&next<='2100-12-31'){month=next;renderCalendar();}}
  function scheduledOn(day){return [...(scheduleCache.get(day)||[])];}
  function renderCalendar(){if(!state)return;monthLabel.textContent=`${month.slice(0,4)}년 ${Number(month.slice(5,7))}월`;calendarGrid.replaceChildren();for(const [index,name]of DAYS.entries())calendarGrid.append(el('span',name,'rv-weekday'+(index===0?' rv-sunday':'')));
    moveBar.hidden=!moving;if(moving)moveBar.replaceChildren(el('p','옮길 날짜를 누르세요. 지난 날짜를 누르면 그날 복습한 걸로 기록해요.'),button('취소',()=>{moving=null;renderCalendar();}));
    const first=schedule.addDays(month,-schedule.dayOfWeek(month));for(let i=0;i<42;i++){const day=schedule.addDays(first,i),scheduled=scheduledOn(day),reviews=state.items.filter(item=>!item.skipped&&item.reviews.includes(day)),learned=state.items.filter(item=>!item.skipped&&item.learned===day),exams=state.exams.filter(exam=>exam.date===day),routines=schedule.routinesOn(state.routines,day);const holiday=state.holidays[day];
      const cell=button(String(Number(day.slice(8))),()=>{selectedDay=day;if(moving)return place(moving,day);renderCalendar();});cell.className='rv-day'+(day.slice(0,7)!==month.slice(0,7)?' rv-outside':'')+(day===selectedDay?' rv-selected':'')+(holiday?' rv-holiday':'')+(schedule.dayOfWeek(day)===0?' rv-sunday':'');cell.dataset.date=day;cell.setAttribute('aria-label',`${md(day)}${holiday?' '+holiday:''} · 복습 ${scheduled.length}개 · 공부 ${learned.length}개${exams.length?' · 시험':''}`);if(day===state.today)cell.setAttribute('aria-current','date');
      const markers=el('span','','rv-markers');for(const row of scheduled.slice(0,6)){const mark=el('span','●','rv-marker'+(row.overdue?' rv-warning':''));mark.title=row.item.subject||row.item.title;if(!row.overdue)mark.style.color=subjectColor(row.item.subject);markers.append(mark);}if(reviews.length)markers.append(el('span','○','rv-marker'));if(learned.length)markers.append(el('span','■','rv-marker'));if(exams.length)markers.append(el('span','◆','rv-marker'));if(routines.length){const done=routines.every(({routine})=>routine.done.includes(day));markers.append(el('span','','rv-marker rv-routine'+(done?' rv-done':day<state.today?' rv-warning':'')));}cell.append(markers);
      cell.ondragover=event=>{if(dragging){event.preventDefault();cell.classList.add('rv-drop');}};cell.ondragleave=()=>cell.classList.remove('rv-drop');cell.ondrop=event=>{event.preventDefault();cell.classList.remove('rv-drop');container.classList.remove('rv-dragging');const id=dragging;dragging=null;if(id&&currentItem(id))void run(()=>place(id,day));};calendarGrid.append(cell);}
    renderDayDetail();}
  function renderDayDetail(){dayDetail.replaceChildren(el('h3',md(selectedDay)));if(state.holidays[selectedDay])dayDetail.append(el('p',state.holidays[selectedDay]+' · 수업 없음','rv-warning'));
    for(const exam of state.exams.filter(row=>row.date===selectedDay))dayDetail.append(el('p','시험 · '+examLabel(exam)));
    for(const {routine}of schedule.routinesOn(state.routines,selectedDay))dayDetail.append(routineCheck(routine,selectedDay));
    for(const item of state.items.filter(row=>!row.skipped&&row.learned===selectedDay))dayDetail.append(el('p','공부 · '+item.title));
    for(const item of state.items.filter(row=>!row.skipped&&row.reviews.includes(selectedDay)))dayDetail.append(el('p','복습함 · '+item.title));
    const rows=scheduledOn(selectedDay);for(const row of rows){const line=el('div','','rv-card');let next='';if(row.item.source==='timetable'&&state.timetable){const nextClass=schedule.nextClassDate(row.item.subject,selectedDay,state.timetable,state.holidays);if(nextClass===schedule.addDays(selectedDay,1))next=' · 다음 날 수업 전';}line.append(el('p',`${row.stage+1}회차 복습${next} · ${row.item.title}`));if(row.stage===row.item.reviews.length){makeDraggable(line,row.item.id);line.append(button('옮기기',()=>beginMove(row.item.id)));}dayDetail.append(line);}
    if(dayDetail.children.length===1)dayDetail.append(el('p','이 날의 기록이 없어요.','rv-muted'));}
  function renderNext(){nextBody.replaceChildren();let count=0;for(let i=1;i<=7;i++){const day=schedule.addDays(state.today,i),rows=scheduledOn(day).sort((a,b)=>itemName(a.item).localeCompare(itemName(b.item),'ko')||a.item.learned.localeCompare(b.item.learned));if(!rows.length)continue;count+=rows.length;const group=el('div','','rv-upcoming-day'),entries=el('div','','rv-upcoming-items');group.append(el('h3',md(day)));for(const row of rows)entries.append(el('p',`${row.item.subject?row.item.subject+' · ':''}${row.item.title} · ${row.stage+1}회차`));group.append(entries);nextBody.append(group);}if(!count)nextBody.append(el('p','7일 안에 예정된 복습이 없어요.','rv-muted'));}
  function renderCurve(){const items=state.items.filter(item=>!item.skipped);if(!items.some(item=>item.id===selectedItem))selectedItem=items[0]?.id||'';curveSelect.replaceChildren();for(const item of items){const option=el('option',item.title);option.value=item.id;curveSelect.append(option);}curveSelect.value=selectedItem;curveSelect.hidden=!items.length;curveBody.replaceChildren();const item=currentItem(selectedItem);if(!item||item.skipped){curveBody.append(el('p','기록을 추가하면 추정 기억 곡선과 회차별 기록이 보여요.','rv-empty'));return;}
    curveBody.append(drawCurve(item),el('p','실선은 지금까지, 점선은 일정대로 복습했을 때의 추정입니다. 옅은 곡선은 복습하지 않았을 때를 뜻해요. 실제 기억력 검사가 아닙니다.','rv-muted'));
    const stages=el('div','','rv-stage-list');stages.append(el('p',`공부·수업한 날 ${md(item.learned)} · 이번 사이클 시작일 ${md(item.base)}`));
    item.reviews.forEach((day,index)=>{const key=item.id+':'+index,row=el('div','','rv-stage'),input=control('date',reviewDrafts.get(key)||day);input.oninput=()=>reviewDrafts.set(key,input.value);input.min=index?item.reviews[index-1]:(item.catchup?item.learned:item.base);input.max=item.reviews[index+1]||state.today;const actions=el('div','','rv-actions');actions.append(label(`${index+1}회차 복습한 날짜`,input),actionButton('날짜 고치기','item.edit_review',()=>({id:item.id,stage:index,date:input.value})));if(index===item.reviews.length-1)actions.append(actionButton('기록 지우기','item.remove_review',{id:item.id}));row.append(actions);stages.append(row);});
    for(const row of schedule.projected(item,state.today)){const stage=el('div','','rv-stage');stage.append(el('p',`${row.stage+1}회차 · ${md(row.date)}${row.overdue?' · 밀림':''}${item.moved?.stage===row.stage?' · 옮김':''}`));if(row.stage===item.reviews.length){const key=item.id+':'+row.stage,input=control('date',placeDrafts.get(key)||row.date);input.min=item.reviews.at(-1)||(item.catchup?item.learned:item.base);const placeButton=button('',()=>place(item.id,input.value));const update=()=>placeButton.textContent=input.value<state.today?'이 날 복습한 걸로 기록':input.value===state.today?'오늘로 당기기':'이 날로 옮기기';input.oninput=()=>{placeDrafts.set(key,input.value);update();};update();const controls=el('div','','rv-actions');controls.append(actionButton('오늘 복습함','item.review',{id:item.id}),label('복습할 날짜',input),placeButton);stage.append(controls);}stages.append(stage);}curveBody.append(stages);}
  function drawCurve(item){const geometry=memoryCurve(item,state.today),host=el('div','','rv-chart'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 560 260');svg.setAttribute('role','img');svg.setAttribute('aria-label',item.title+'의 추정 기억률 곡선');
    const node=(name,attrs,content='')=>{const element=document.createElementNS('http://www.w3.org/2000/svg',name);for(const [key,value]of Object.entries(attrs))element.setAttribute(key,String(value));element.textContent=content;svg.append(element);return element;};const x=t=>42+t/geometry.end*502,y=r=>28+(1-Math.max(0,Math.min(1,r)))*202,path=points=>points.map((p,i)=>(i?'L':'M')+x(p.t).toFixed(1)+' '+y(p.r).toFixed(1)).join(' ');
    for(const value of [0,.25,.5,.75,1]){node('line',{class:'rv-grid',x1:42,x2:544,y1:y(value),y2:y(value)});node('text',{x:34,y:y(value)+4,'text-anchor':'end'},value*100+'%');}
    const step=[1,2,3,7,14,30,60,90,180].find(step=>step*502/geometry.end>=50)||365;for(let i=0;i<=geometry.end;i+=step)node('text',{x:x(i),y:249,'text-anchor':'middle'},md(schedule.addDays(geometry.base,i)).split(' ')[0]);
    node('path',{class:'rv-baseline',d:path(geometry.baseline)});node('path',{class:'rv-past',d:path(geometry.past)});node('path',{class:'rv-future',d:path(geometry.future)});geometry.events.forEach((t,i)=>{node('circle',{cx:x(t),cy:y(1),r:3});if(i)node('text',{x:x(t),y:15,'text-anchor':'middle'},String(i));});if(geometry.todayT>=0){node('line',{class:'rv-today-line',x1:x(geometry.todayT),x2:x(geometry.todayT),y1:28,y2:230});node('text',{x:Math.min(440,x(geometry.todayT)+6),y:45},`오늘 ${Math.round(geometry.remembered*100)}%`);}host.append(svg);return host;}
  function renderRoutines(){routineBody.replaceChildren();const rows=state.routines.map(routine=>({routine,stats:schedule.routineStats(routine,state.today)})).sort((a,b)=>Number(a.stats.ended)-Number(b.stats.ended));for(const {routine,stats}of rows){const card=el('article','','rv-card rv-routine-row'+(stats.ended?' rv-ended':'')),main=el('div','','rv-routine-main');main.append(el('h3',routine.name),el('p',`${routine.tag?routine.tag+' · ':''}${schedule.routineDaysLabel(routine)} · ${md(routine.start)}${routine.end?' ~ '+md(routine.end):''}`,'rv-muted'));card.append(main,el('p',`${routine.count?`진행 ${stats.total} / ${routine.count}`:`이번 주 ${stats.week_done} / ${stats.week_total}`} · 연속 ${stats.streak}번${stats.ended?' · 끝남':''}`,'rv-routine-stats'));const actions=el('div','','rv-actions');if(!stats.ended)actions.append(actionButton('그만하기','routine.stop',{id:routine.id}));actions.append(confirmButton('삭제','routine:'+routine.id,'routine.delete',{id:routine.id}));card.append(actions);routineBody.append(card);}if(!rows.length)routineBody.append(el('p','매일 또는 정한 요일의 공부를 루틴으로 남겨 보세요.','rv-muted'));}
  function renderExams(){examBody.replaceChildren();for(const exam of [...state.exams].sort((a,b)=>a.date.localeCompare(b.date))){const {sessions,stats,sem}=examInfo(exam),range=schedule.examRange(exam,sem,state.exams),card=el('article','','rv-card');const skipped=sessions.filter(row=>row.skipped).length;
    card.append(el('h3',examLabel(exam)),badge(`${md(exam.date)} · ${stats.days_left===0?'D-day':stats.days_left>0?'D-'+stats.days_left:'종료'}`,['cram','today'].includes(stats.phase)),el('p',`범위 ${schedule.weekNo(range.start,sem)}주차 ${md(range.start)} ~ ${schedule.weekNo(range.end,sem)}주차 ${md(range.end)} · 수업 ${sessions.length-skipped}회 (건너뛴 수업 ${skipped}회 제외) · ${exam.rounds}회독`));
    for(let round=0;round<exam.rounds;round++){const count=stats.per[round];const p=el('progress');p.max=sessions.length-skipped||1;p.value=count;p.setAttribute('aria-label',`${round+1}회독 ${count}/${sessions.length-skipped}`);card.append(el('p',`${round+1}회독 ${count}/${sessions.length-skipped}`),p);}
    card.append(el('p',stats.phase==='cram'?`오늘 회독 목표 ${stats.target}개 · 남은 ${stats.remaining}개`:stats.phase==='before'?`${md(stats.cram_start)}부터 벼락치기를 시작해요.`:stats.phase==='today'?'오늘 시험이에요. 정리한 내용을 확인하세요.':'시험이 끝났어요.'));
    if(stats.next_key){const next=sessions.find(row=>row.key===stats.next_key);if(next)card.append(el('p',`다음: ${stats.next_round+1}회독 · ${next.title}`));}
    const details=el('details'),table=el('div','','rv-exam-table');details.open=stats.phase==='cram';details.append(el('summary','회독표 보기'),table);for(const row of sessions){const line=el('div','','rv-exam-session');const title=el('span',`${row.week}주차 · ${md(row.date)} · ${row.title}${row.future?' · 예정':''}`,row.skipped?'rv-struck':'');line.append(title);for(let round=0;round<exam.rounds;round++){const cell=check(`${round+1}회독`,!!exam.done[row.key]?.[round]);cell.node.disabled=row.future||!!row.skipped||busy||!!intent;const captured=context;cell.node.onchange=()=>run(()=>valid(captured)&&mutate('exam.check',{id:exam.id,session_key:row.key,round,checked:cell.node.checked}));line.append(cell.wrapper);}table.append(line);}card.append(details,confirmButton('시험 삭제','exam:'+exam.id,'exam.delete',{id:exam.id}));examBody.append(card);}if(!state.exams.length)examBody.append(el('p','시험을 등록하면 범위 안의 수업과 벼락치기 회독표를 만들어요.','rv-muted'));}
  function subjectColor(subject){let hash=0;for(const c of String(subject))hash=(hash*31+c.codePointAt(0))>>>0;return ['#4f8064','#9b713e','#6879a0','#977389','#5d8c91','#8c834c'][hash%6];}
  function weekGrid(classes){const holder=el('div','','rv-stack'),grid=el('div','','rv-week-grid'),times=classes.filter(row=>/^\d\d:\d\d$/.test(row.start)&&/^\d\d:\d\d$/.test(row.end)&&row.end>row.start);
    const minutes=value=>Number(value.slice(0,2))*60+Number(value.slice(3)),startHour=Math.min(9,...times.map(row=>Math.floor(minutes(row.start)/60))),endHour=Math.max(18,...times.map(row=>Math.ceil(minutes(row.end)/60))),slots=(endHour-startHour)*4;
    const axis=el('div','','rv-week-axis');axis.append(el('strong','시간'));const ticks=el('div','','rv-week-track');ticks.style.gridTemplateRows=`repeat(${slots},minmax(14px,auto))`;for(let hour=startHour;hour<endHour;hour++){const tick=el('small',String(hour).padStart(2,'0')+':00');tick.style.gridRow=String((hour-startHour)*4+1)+' / span 4';ticks.append(tick);}axis.append(ticks);grid.append(axis);
    for(let i=1;i<=7;i++){const day=i%7,column=el('div','','rv-week-column'),track=el('div','','rv-week-track');column.append(el('strong',DAYS[day]));track.style.gridTemplateRows=`repeat(${slots},minmax(14px,auto))`;for(const row of times.filter(row=>Number(row.day)===day).sort((a,b)=>a.start.localeCompare(b.start))){const block=el('div','','rv-class-block');block.style.borderLeftColor=subjectColor(row.subject);const begin=Math.floor((minutes(row.start)-startHour*60)/15)+1,end=Math.ceil((minutes(row.end)-startHour*60)/15)+1;block.style.gridRow=`${begin} / ${end}`;block.append(el('strong',row.subject||'과목 입력'),el('p',`${row.start}–${row.end}`),el('small',row.room||''));track.append(block);}column.append(track);grid.append(column);}holder.append(grid);
    const unknown=classes.filter(row=>!times.includes(row));if(unknown.length)holder.append(el('p','시간 확인 필요: '+unknown.map(row=>`${DAYS[Number(row.day)]} ${row.subject||'과목 입력'} ${row.start||'?'}–${row.end||'?'}`).join(' · '),'rv-muted'));return holder;}
  function renderTimetable(){timetableView.replaceChildren();const tt=state.timetable;if(!tt){timetableView.append(el('p','시간표를 등록하면 오늘까지의 수업이 자동으로 복습 기록에 쌓여요.','rv-muted'),button('시간표 등록',()=>openEditor()));return;}
    timetableView.append(el('p',`매주 수업 ${tt.classes.length}개 · ${md(tt.from)}부터${tt.until?' '+md(tt.until)+'까지':''}`),el('p','공휴일과 시험 날은 건너뛰어요.','rv-muted'));const todayClasses=tt.classes.filter(row=>row.day===schedule.dayOfWeek(state.today)&&!state.holidays[state.today]&&!state.exams.some(exam=>exam.subject===row.subject&&exam.date===state.today));timetableView.append(el('p','오늘 수업: '+(todayClasses.map(row=>`${row.subject} ${row.start}`).join(' · ')||'없음')));
    const actions=el('div','','rv-actions');actions.append(button('지난 수업 불러오기',()=>{catchupPanel.hidden=false;catchupStart.value=state.settings.sem_start||tt.from;previewCatchup();}),button('시간표 수정',()=>openEditor()),confirmButton('자동 등록 끄기','timetable','timetable.disable',{}));timetableView.append(actions,el('h3','평소 복습 방식'));
    const presets=el('div','','rv-actions'),modeForm=el('div','','rv-stack'),modeChecks={};for(const [name,mode]of MODES)presets.append(button(name,()=>{for(const key of Object.keys(modeChecks))modeChecks[key].checked=mode[key];modeDraft=clone(mode);updateExample();}));modeForm.append(presets);const toggles=el('div','','rv-chips');for(const [key,name]of Object.entries(MODE_LABELS)){const c=check(name,(modeDraft||tt.mode)[key]);modeChecks[key]=c.node;c.node.onchange=()=>{modeDraft=readMode();if(Object.values(modeDraft).some(Boolean))updateExample();else example.textContent='복습 방식을 하나 이상 선택해 주세요.';};toggles.append(c.wrapper);}const example=el('p','','rv-muted'),apply=check(`이미 있는 수업 기록 ${state.items.filter(item=>item.source==='timetable'&&!item.skipped&&schedule.nextDue(item)).length}개에도 적용할까요?`,modeApply);apply.node.onchange=()=>{modeApply=apply.node.checked;};modeForm.append(toggles,example,apply.wrapper,button('복습 방식 저장',()=>{const mode=readMode();if(!Object.values(mode).some(Boolean))throw Error('복습 방식을 하나 이상 선택해 주세요.');return mutate('timetable.mode',{mode,apply_existing:apply.node.checked});}));
    function readMode(){return Object.fromEntries(Object.entries(modeChecks).map(([key,node])=>[key,node.checked]));}function exampleLesson(){const off=schedule.holidayMap(state.holidays);for(let n=0;n<14;n++){const day=schedule.addDays(state.today,n);if(day<tt.from||(tt.until&&day>tt.until)||Object.hasOwn(off,day))continue;const rows=tt.classes.filter(row=>row.day===schedule.dayOfWeek(day)&&!state.exams.some(exam=>exam.subject===row.subject&&exam.date===day)).sort((a,b)=>(a.start||'').localeCompare(b.start||''));if(rows.length)return {row:rows[0],day};}return null;}function updateExample(){const lesson=exampleLesson();if(!lesson){example.textContent='';return;}const mode=readMode();if(!Object.values(mode).some(Boolean)){example.textContent='복습 방식을 하나 이상 선택해 주세요.';return;}const {row,day}=lesson,offsets=schedule.offsetsFor(row.subject,day,{...tt,mode},state.settings,state.holidays);example.textContent=`${md(day)} ${row.subject} 수업이면 → ${offsets.map(offset=>md(schedule.addDays(day,offset))).join(' · ')}에 복습해요.`;}updateExample();timetableView.append(modeForm,weekGrid(tt.classes));}
  function openEditor(){editorVisible=true;timetableEditor.hidden=false;timetableView.hidden=true;if(!editorDirty){classRows.replaceChildren();for(const row of state.timetable?.classes||[])addClassRow(row,false);if(!classRows.children.length)addClassRow({},false);ttFrom.value=state.timetable?.from||state.today;ttUntil.value=state.timetable?.until||'';editorDirty=false;}renderWeekPreview();}
  function addClassRow(value={},dirty=true){if(classRows.children.length>=60)throw Error('수업은 최대 60개까지 등록할 수 있어요.');const row=el('div','','rv-class-row'),subject=control('text',value.subject||'',40),day=select(DAYS.map((name,index)=>[index,name]),value.day??1),start=control('time',value.start||''),end=control('time',value.end||''),room=control('text',value.room||'',120);subject.required=true;row._fields={subject,day,start,end,room};for(const [name,node]of [['과목',subject],['요일',day],['시작',start],['끝',end],['강의실',room]]){node.oninput=node.onchange=()=>{editorDirty=true;editorRevision++;renderWeekPreview();};row.append(label(name,node));}row.append(button('빼기',()=>{row.remove();editorDirty=true;editorRevision++;renderWeekPreview();}));classRows.append(row);if(dirty){editorDirty=true;editorRevision++;}renderWeekPreview();}
  function readClassRows(){return [...classRows.children].map(row=>{const f=row._fields;return {subject:f.subject.value.trim(),day:Number(f.day.value),start:f.start.value,end:f.end.value,room:f.room.value.trim()};});}
  function renderWeekPreview(){weekPreview.replaceChildren(weekGrid(readClassRows()));}
  ttFrom.oninput=ttUntil.oninput=()=>{editorDirty=true;editorRevision++;};
  async function parseTimetable(kind){if(parseBusy||busy||intent||state.recognition?.enabled!==true)return;const captured=context,revision=editorRevision;let body,headers;
    if(kind==='text'){if(!parseText.value.trim()||parseText.value.length>6000)throw Error('시간표 글을 1~6,000자로 입력해 주세요.');body=JSON.stringify({text:parseText.value});headers={'Content-Type':'application/json'};}
    else{const file=parseFile.files?.[0];if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('PNG, JPEG, WebP 이미지 한 개를 10MB 이하로 선택해 주세요.');body=file;headers={'Content-Type':file.type};}
    parseBusy=true;parseStatus.textContent='시간표를 읽고 있어요. 결과를 확인한 뒤 저장해 주세요.';try{const result=await request('/review/timetable/parse',{method:'POST',headers,body},captured,80000);if(editorRevision!==revision){parseStatus.textContent='인식하는 동안 직접 입력한 내용이 바뀌어 결과를 덮어쓰지 않았어요. 필요하면 다시 인식해 주세요.';return;}if(!Array.isArray(result?.classes)||result.classes.length>60||!result.classes.every(row=>text(row.subject,40)&&Number.isInteger(row.day)&&row.day>=0&&row.day<=6&&text(row.start,5)&&text(row.end,5)&&text(row.room||'',120)))throw Error('인식 결과를 확인하지 못했습니다. 직접 입력해 주세요.');classRows.replaceChildren();for(const row of result.classes)addClassRow(row,false);editorDirty=true;editorRevision++;parseFile.value='';parseStatus.textContent=`${result.classes.length}개 수업을 읽었어요. 과목·요일·시간을 확인하고 시간표 저장을 눌러 주세요. 아직 저장하지 않았습니다.`;}
    finally{if(valid(captured)){parseBusy=false;scheduleRefresh();}}}
  function previewCatchup(){if(!state.timetable)return;catchupRows=schedule.catchupPreview(state.timetable,catchupStart.value,state.today,state.settings,state.holidays,state.source_keys||state.items.map(item=>item.source_key).filter(Boolean),state.exams);catchupChoices.replaceChildren();catchupPerLabel.hidden=!!state.timetable.mode.eve;const weeks=new Map();for(const row of catchupRows){if(!weeks.has(row.week)){const box=el('div','','rv-stack'),chips=el('div','','rv-catchup-week');box.append(el('h4',row.week+'주차'),chips);weeks.set(row.week,chips);catchupChoices.append(box);}const c=check(`${md(row.date)} ${row.subject}${row.holiday?' · '+row.holiday:''}${row.existing?' · 이미 있음':''}`,row.selected&&!row.existing);c.node.disabled=row.existing;c.node.onchange=()=>{row.selected=c.node.checked;updateCatchupSummary();};weeks.get(row.week).append(c.wrapper);}updateCatchupSummary();}
  function updateCatchupSummary(){if(!state.timetable)return;const plan=schedule.catchupPlan(catchupRows,state.timetable,state.today,state.settings,state.holidays,Number(catchupPerDay.value));if(!plan.length){catchupSummary.textContent='불러올 수업을 선택해 주세요.';return;}catchupSummary.textContent=state.timetable.mode.eve?`수업 ${plan.length}개를 불러와요. 과목마다 다음 수업 전날에 따라잡기 복습을 해요. `+[...new Set(plan.map(row=>`${row.subject} ${md(row.base)}`))].join(' · '):`수업 ${plan.length}개를 불러와요. 오늘부터 ${md(plan.at(-1).base)}까지 오래된 수업부터 나눠서 따라잡기 복습을 해요.`;}
  async function saveCatchup(){const keys=catchupRows.filter(row=>row.selected&&!row.existing).map(row=>row.source_key);if(!keys.length)throw Error('불러올 수업을 선택해 주세요.');if(await mutate('timetable.catchup',{sem_start:catchupStart.value,source_keys:keys,per_day:Number(catchupPerDay.value)})){previewCatchup();message(`${keys.length}개 수업을 불러왔어요. 이미 있는 수업은 다시 만들지 않습니다.`);}}
  function renderRecords(){if(!state)return;for(const b of recordsBar.children)if(b.dataset?.filter)b.setAttribute('aria-pressed',String(b.dataset.filter===filter));recordsSubjects.replaceChildren(button('모든 과목',()=>{subjectFilter='';renderRecords();}));for(const subject of [...new Set(state.items.map(item=>item.subject))].sort((a,b)=>a.localeCompare(b,'ko'))){const b=button(subject||'과목 없음',()=>{subjectFilter=subject||'__none';renderRecords();});b.setAttribute('aria-pressed',String(subjectFilter===(subject||'__none')));recordsSubjects.append(b);}
    const wanted=query.trim().toLocaleLowerCase(),rows=state.items.filter(item=>filter==='all'||filter==='skipped'?filter==='all'||!!item.skipped:!item.skipped&&(filter==='done'?!schedule.nextDue(item):!!schedule.nextDue(item))).filter(item=>!subjectFilter||item.subject===(subjectFilter==='__none'?'':subjectFilter)).filter(item=>!wanted||`${item.title} ${item.subject} ${item.memo}`.toLocaleLowerCase().includes(wanted)).sort((a,b)=>b.learned.localeCompare(a.learned));recordsBody.replaceChildren(el('p',`${rows.length}개 기록`));if(filter==='skipped'){recordsBody.append(el('p','남은 복습 일정에서 제외한 항목이에요. 복습 다시 시작을 누르면 원래 일정으로 돌아갑니다.','rv-muted'));if(!rows.length)recordsBody.append(el('p',wanted||subjectFilter?'조건에 맞는 건너뛴 복습이 없어요.':'건너뛴 복습이 없어요.','rv-empty'));}for(const item of rows.slice(0,recordsLimit))recordsBody.append(itemCard(item,{records:true}));if(rows.length>recordsLimit)recordsBody.append(button('다음 50개 더 보기',()=>{recordsLimit+=50;renderRecords();}));}
  const visibility=()=>{if(visible&&document.visibilityState!=='hidden')void run(()=>refresh());};document.addEventListener?.('visibilitychange',visibility);win.addEventListener?.('focus',visibility);
  function destroy(){reset();destroyed=true;document.removeEventListener?.('visibilitychange',visibility);win.removeEventListener?.('focus',visibility);container.onkeydown=null;}
  reset();return {open,reset,hide,destroy,refresh:()=>run(()=>refresh())};
}
